apiVersion: apps/v1
kind: Deployment
metadata:
  name: argostudy-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argostudy
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argostudy
    spec:
      containers:
        - image: moony1204/argostudy
          imagePullPolicy: Always
          name: argoStudy
          ports:
            - containerPort: 80